modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "minecolonies_tfc_compat"
    version = "${mod_version}"
    displayName = "MineColonies TFC Compat"
    description = "Maps TerraFirmaCraft tool tiers to the correct MineColonies equipment levels."

[[dependencies.minecolonies_tfc_compat]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minecolonies_tfc_compat]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minecolonies_tfc_compat]]
    modId = "minecolonies"
    type = "required"
    versionRange = "[*,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.minecolonies_tfc_compat]]
    modId = "tfc"
    type = "required"
    versionRange = "[*,)"
    ordering = "AFTER"
    side = "BOTH"
